-- SPDX-FileCopyrightText: Iridesium
-- SPDX-License-Identifier: GPL-3.0-only
--
-- Every block Spindle places, one per layer, with a flat placeholder texture.
--
-- The point of this pass is to be able to fly through the world and SEE the
-- layers, so each one gets its own colour and nothing more. Real textures,
-- sounds and hardness are a later pass; the ids are what the rest of the mod
-- depends on and they do not change.
--
-- `textures/*.png` are generated by ../../tools/make_textures.py from the
-- colours in that script — edit it there, not by hand.
--
-- `tint` is the engine's large-scale colour field: the client multiplies a
-- texture by a smooth function of WORLD position, the same field for every
-- material, so a hillside varies as a hillside. `strength` moves the tone;
-- `low`/`high` are RGB multipliers at the two ends of the field for a hue
-- shift. `scale` is the period in blocks. Presentation only.

local M = {}

-- Footsteps come from the core reference set: a qualified id is used as-is.
local STEP = { step = "core:step" }

-- Tone-only variation for rock; a hue shift for anything that grows.
-- Doubled in both period and strength on 2026-09-10, from the window: at
-- half this it read as texture rather than as ground changing across a hill.
local ROCK = { strength = 0.20, scale = 128 }
local SOIL = { strength = 0.28, scale = 96 }
local GREEN = { strength = 0.32, scale = 192, low = { 0.76, 1.0, 0.64 }, high = { 1.0, 0.90, 0.66 } }
-- The highlands' grass: darker, bluer, and barely shifting — the cold
-- end of the green.
local COLD_GREEN = { strength = 0.16, scale = 192, low = { 0.86, 1.0, 0.98 }, high = { 0.92, 0.94, 1.0 } }
-- The ice: cold blue, shifting between a deeper blue and a paler one.
local COLD_BLUE = { strength = 0.18, scale = 96, low = { 0.80, 0.90, 1.0 }, high = { 1.0, 1.0, 1.0 } }

local function block(id, name, description, extra)
    local spec = {
        id = id,
        name = name,
        description = description,
        textures = { all = "textures/" .. id .. ".png" },
        sounds = STEP,
    }
    if extra then
        for key, value in pairs(extra) do
            spec[key] = value
        end
    end
    -- `register_block` hands back the per-session numeric id, which is what
    -- the native fills take. Never persisted, never compared to a literal.
    M[id] = game.register_block(spec)
    return M[id]
end

-- Surface ---------------------------------------------------------------
block("stone", "Stone", "The body of the world.", { hardness = 1.5, tint = ROCK })
block("dirt", "Dirt", "Ground with no biome claim on it yet.", { hardness = 0.5, tint = SOIL })
block("packed_dirt", "Packed dry dirt", "A game trail; a bared crest.", { hardness = 0.7, tint = SOIL })
block("grass", "Grass", "Temperate turf.", { hardness = 0.5, tint = GREEN })
block("mud", "Mud", "The floor of a pool.", { hardness = 0.4, tint = SOIL })
block("gravel", "Gravel", "Loose gravel: creek beds, moraine, shingle, frost-sorted troughs.", { hardness = 0.6, tint = ROCK })
block("granite", "Granite", "Weathered, grey, speckled.", { hardness = 2.0, tint = ROCK })
block("oak_log", "Oak log", "Trunk of a temperate oak.", { hardness = 1.0, tint = SOIL })
block("birch_log", "Birch log", "Pale, papery bark.", { hardness = 0.9, tint = ROCK })
block("dead_log", "Dead log", "Grey, dry, split.", { hardness = 0.6, tint = ROCK })
-- Alpine highlands (1.3), asked for by name: slate seams in the granite,
-- permafrost in patches, and snow as a crust one cell thick (a cover).
block("slate", "Slate", "Dark, layered, splits in sheets.", { hardness = 1.4, tint = ROCK })
block("permafrost", "Permafrost", "Ground frozen hard, grey-brown.", { hardness = 0.9, tint = SOIL })
block("snow", "Packed snow", "Eight blocks of it over everything above the snowline, standing four over the ground.", { hardness = 0.2, tint = ROCK })
block("ice", "Glacier ice", "The valley floors and cirques above the snowline.", { hardness = 0.8, tint = COLD_BLUE })
-- Firs, for the highlands' tree line (asked for 2026-09-12): a dark
-- trunk and needles in the leaves' round-dot look, a darker blue-green.
block("fir_log", "Fir log", "Trunk of a mountain fir.", { hardness = 1.0, tint = SOIL })
block("fir_needles", "Fir needles", "Tiers of them, dark.", { hardness = 0.2, tint = GREEN, cutout = true, sway = true })
-- The highlands' own grass (asked for 2026-09-12): the temperate tuft's
-- blades in a darker, desaturated blue-green, with its own cold tint — a
-- tint is per material, so a different hue is a different block.
-- The highlands' turf: the `grass` block's role in the temperate ring, in
-- the same cold blue-green as the tufts that stand on it (2026-09-12).

-- Ground cover. Cells, not blocks: a fern is two cell layers of a block, a
-- tuft of grass one to three, a bramble a tangle of cells over a few
-- blocks. Ferns and grass are `passable` — a body walks through them, and
-- a ray still stops at them so they can be broken; brambles are meant to
-- be walked round, so they are not. Grass and the flowers are `billboard =
-- "cross"`: a run of cells in a column is drawn as TWO fixed cards on the
-- diagonals of its column, each as tall as the run and the whole tile
-- across — the X Minecraft and Minetest draw, which holds still as the
-- player walks round it (a turning card read as a sticker following you:
-- engine-asks item 9, landed 2026-09-11). The cells are kept for
-- everything else. **A billboard is NOT
-- also `cutout`**: cutout is a rule for culling cube faces, a sprite has
-- none, and the mesher takes billboard cells out of the opaque set but
-- not out of the cutout set (engine-asks, item 13) — declared both, the
-- grass was drawn as cutout cubes with the sprite lost inside them. The
-- sprite pass alpha-tests on its own. Ferns stay geometry, in the
-- round-dot look. Everything soft sways.
block("fern", "Fern", "Knee-high, in carpets.", { hardness = 0.1, tint = GREEN, cutout = true, passable = true, sway = true })
block("tall_grass", "Tall grass", "Tufts of it.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })
block("bramble", "Bramble", "Wild berry canes, tangled.", { hardness = 0.3, tint = GREEN, billboard = "cross" })
-- Lady's mantle: a low rosette of rounded leaves, and its bloom — sprays of
-- tiny chartreuse flowers, its own colour, placed above a leaf cell so a
-- patch reads as leaves with blooms rising from them.
block("ladys_mantle", "Lady's mantle", "A rosette of scalloped leaves.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })
block("ladys_mantle_bloom", "Blooming lady's mantle", "Sprays of tiny chartreuse flowers.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })
-- The meadow flowers (2026-09-14: "rare Roman chamomile* and fairly common
-- blue lunaria everywhere"), in every grassy biome's cover beside the grass
-- (`tdw.flower_covers`, biomes.lua). Chamomile asked for by name; lunaria
-- had no block either. A tone-only tint, so the blue stays blue and the
-- white white where the grass's hue shift would have greened them.
block("blue_lunaria", "Blue lunaria", "Tall sprays of small violet-blue flowers.", { hardness = 0.1, tint = { strength = 0.12, scale = 96 }, passable = true, sway = true, billboard = "cross" })
block("roman_chamomile", "Roman chamomile", "Low white daisies with yellow hearts; smells of apples when trodden.", { hardness = 0.1, tint = { strength = 0.12, scale = 96 }, passable = true, sway = true, billboard = "cross" })
-- Rose bushes (grasslands, 2026-09-11). A bush is a rough ellipsoid of
-- `rose_bush` cells with a few `rose_blooms` cells over its top: two
-- materials in one block, because every texture is one colour (the blooms
-- are red and the bush is not) and a run of billboard cells is one card
-- per material, so the blooms read as red dots sitting on the leaves.
-- Neither is passable — a bush is walked round. Picking is a dig on a bush
-- that has blooms (the engine has no right-click hook yet: engine-asks,
-- item 16): the bloom cells turn to bush, the player is given a rose or
-- two, and the blooms come back after a while (`rolling_grasslands.lua`).
block("rose_bush", "Rose bush", "A rounded thorny bush.", { hardness = 0.4, tint = GREEN, sway = true, billboard = "cross" })
block("rose_blooms", "Roses", "Blooms on a rose bush. Pick them.", { hardness = 0.1, tint = GREEN, sway = true, billboard = "cross" })
-- The rose itself is an ITEM: carried, never placed. Its texture is a
-- picture, which is what an item is (the flat-colour rule is for the world).
M.rose = game.register_item{ id = "rose", name = "Rose", description = "Picked from a bush.", texture = "textures/rose.png" }
-- Cutout, not transparent: the OPPOSITE culling rule. Glass hides the face
-- between two panes; foliage keeps the faces between two leaf blocks,
-- because culled, a canopy is a hollow shell whose alpha holes look straight
-- through at the sky. Alpha-tested with the opaque world, so it writes
-- depth and needs no sorting. The texture's alpha is binary (see
-- tools/make_textures.py): every sub-node face is a 3x3 of pixels, each
-- opaque or gone at random.
block("oak_leaves", "Oak leaves", "Canopy of a temperate oak.", { hardness = 0.2, tint = GREEN, cutout = true, sway = true })

-- The coast (1.4). Two new nodes, asked for by name: the dark basalt of
-- the strata and the dead coral of the splash zone. The sandstone stratum
-- is `stone` standing in (one new material a biome is the rule, and
-- two were asked for); the gravel is `gravel`.
block("dark_basalt", "Dark basalt", "A near-black stratum of the sea cliffs.", { hardness = 1.6, tint = ROCK })
block("dead_coral", "Dead coral", "Bleached, pitted, slick: the splash zone's crust.", { hardness = 0.7, tint = SOIL })
-- The cliff-top flora, light yellow-green: a tint is per material, so a
-- hue is a block (as the alpine's cold green was), and the chunk tint
-- would carry the strata with it.
local YELLOW_GREEN = { strength = 0.22, scale = 160, low = { 0.92, 1.0, 0.62 }, high = { 1.0, 0.96, 0.70 } }
-- The coastal shelf, the coast's sea side (2026-09-13). Four asked for by
-- name — the moss, the barnacles, the seagrass and the kelp — and sand,
-- which the shelf's floor is and nothing here could stand in for. The
-- seagrass and the kelp are cross cards like the grasses, stacked block
-- on block by the scatter; a card block holds three cells of its
-- twenty-seven, so the sea fill puts water round it and it sways in the
-- sea rather than in a bubble.
block("sand", "Sand", "The shelf's floor, and the drifts along the beaches.", { hardness = 0.4, tint = SOIL })
block("ocean_moss", "Ocean moss", "A thin dark coat on the wave-scoured rock flats.", { hardness = 0.3, tint = COLD_GREEN })
block("barnacles", "Barnacles", "A pale crust on the rock flats and the wave-rounded boulders.", { hardness = 0.6, tint = ROCK })
block("seagrass", "Seagrass", "Two to four blocks of it, swaying with the current.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })
block("kelp", "Kelp", "Ten blocks of it from a hollow, swaying.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })

-- The river valleys (1.6). Five new nodes, asked for by name: the willow's
-- wood, its leaves and its planks, and the two flowering herbs of the bank.
-- The clay beds are `wet_clay` (since 2026-09-14; `mud` before), the gravel
-- is `gravel` and the bedrock shelves are `stone`.
block("willow_log", "Willow log", "Grey-brown, twisted, and always leaning over the water.", { hardness = 0.9, tint = SOIL })
block("willow_leaves", "Willow leaves", "Long curtains of it, dipping into the current.", { hardness = 0.2, tint = GREEN, cutout = true, sway = true })
block("willow_planks", "Willow planks", "Pale boards cut from a river willow.", { hardness = 0.8, tint = SOIL })
block("water_iris", "Water iris", "Blades and a flower, standing in the shallows.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })
block("wild_mint", "Wild mint", "Low, soft, and everywhere the bank is damp.", { hardness = 0.1, tint = GREEN, passable = true, sway = true, billboard = "cross" })

-- The Dense Rainforest Canopy (1.7). Seven new nodes, all asked for by name
-- (2026-09-14): moss*, black mud*, ironwood* with its leaves and planks,
-- climbing ivy* and monsteras*; and six more named the same evening: the
-- pitcher plants, the kapok's wood, leaves and planks, and dry and wet clay.
-- The rest of the brief is nodes that already exist: the saturated mud is
-- `mud`, the grass `grass`, the rare outcrops `stone` under moss, the fan
-- palms the river palm's `willow_log` and `oak_leaves`, the tree ferns
-- `oak_log` and `fern`, and the hanging vines `climbing_ivy`.
local EMERALD = { strength = 0.24, scale = 160, low = { 0.78, 1.0, 0.82 }, high = { 0.90, 1.0, 0.88 } }
block("moss", "Moss", "A thick wet coat over the rainforest floor, and over nearly every stone in it.", { hardness = 0.3, tint = EMERALD })
block("black_mud", "Black mud", "Deep sucking puddles of it in the hollows and the sinkholes.", { hardness = 0.4, tint = SOIL })
block("ironwood_log", "Ironwood log", "A megatree's trunk: dark, dense, nearly as hard as stone.", { hardness = 2.2, tint = SOIL })
block("ironwood_leaves", "Ironwood leaves", "The high canopy, dark and layered.", { hardness = 0.2, tint = EMERALD, cutout = true, sway = true })
block("ironwood_planks", "Ironwood planks", "Heavy red-brown boards cut from an ironwood.", { hardness = 1.8, tint = SOIL })
block("climbing_ivy", "Climbing ivy", "Up every trunk, and hanging in ropes from the limbs.", { hardness = 0.1, tint = EMERALD, passable = true, sway = true, billboard = "cross" })
block("monstera", "Monstera", "Giant split leaves on the forest floor.", { hardness = 0.1, tint = EMERALD, passable = true, sway = true, billboard = "cross" })
block("pitcher_plant", "Pitcher Plants", "Carnivorous tubes huddled in the hollows between a megatree's roots.", { hardness = 0.1, tint = EMERALD, passable = true, billboard = "cross" })
block("kapok_log", "Kapok log", "The emergent's trunk: pale, smooth and grey.", { hardness = 1.0, tint = ROCK })
block("kapok_leaves", "Kapok leaves", "Flat tiers of lighter green high over the canopy.", { hardness = 0.2, tint = GREEN, cutout = true, sway = true })
block("kapok_planks", "Kapok planks", "Light, pale boards cut from a kapok.", { hardness = 0.7, tint = SOIL })
block("dry_clay", "Dry clay", "Cracked pale clay, up the walls of the ravines.", { hardness = 0.8, tint = SOIL })
block("wet_clay", "Wet clay", "Slick dark clay where the water sits: a ravine's floor, a river's bank.", { hardness = 0.5, tint = SOIL })

-- The Deep Ocean (1.8). One new node, asked for by name (2026-09-14): bone,
-- for the whale skeletons. Everything else is a node that exists: `sand`,
-- `mud`, `dark_basalt`, `gravel` (the gravel drifts), `magma` (in the
-- cracks: it already glows), and the vents' `barnacles`, `ocean_moss`,
-- `kelp` and `seagrass`. Stand-ins until named: white sand is `stone`,
-- fine dark sand `black_mud`.
block("bone", "Bone", "A whale's, long on the sea floor, broken across the basalt.", { hardness = 1.2, tint = ROCK })

-- The Frozen Wastes (1.9). One new node, asked for by name (2026-09-14):
-- clear ice, for the cryo-lakes. Everything else exists: `snow`, the blue
-- glacial `ice`, `permafrost`, `gravel` (the frost-heaved gravel of the
-- polygons), `granite` (the erratics) and `dead_log` (the frozen snags).
block("clear_ice", "Clear ice", "A frozen lake's top: deep, clear, and blue under it.", { hardness = 0.8, tint = COLD_BLUE, transparent = true })

-- The Arid Mesa (2.0). Six new nodes, asked for by name (2026-09-14):
-- rust-red* and ochre* sandstone, pale terracotta*, the juniper's* wood and
-- needles, and the columnar cactus*. Stand-ins until named: terracotta is
-- `dry_clay`, pale tan sandstone `stone`, desert sandstone and red sand
-- `sand`, sagebrush `bramble`; the barrel cacti and prickly pear are cut
-- from the columnar cactus; the palms are the river's `willow_log` and
-- `oak_leaves`; the pines share the juniper's nodes.
block("rust_red_sandstone", "Rust-red sandstone", "The mesa's reddest strata.", { hardness = 1.3, tint = ROCK })
block("ochre_sandstone", "Ochre sandstone", "Yellow-brown bands between the red.", { hardness = 1.3, tint = ROCK })
block("pale_terracotta", "Pale terracotta", "The hard cap on a mesa's top, and on a hoodoo's.", { hardness = 1.6, tint = ROCK })
block("juniper_log", "Juniper log", "Crooked, split and weathered grey.", { hardness = 1.0, tint = ROCK })
block("juniper_needles", "Juniper needles", "Flat, sparse pads of dark evergreen.", { hardness = 0.2, tint = COLD_GREEN, cutout = true, sway = true })
block("cactus", "Cactus", "Ribbed green columns with right-angle arms.", { hardness = 0.4, tint = GREEN })

-- The Badlands (2.1). Four new nodes, asked for by name (2026-09-14):
-- volcanic ash*, charcoal*, dull lavender dried mud* and dead sagebrush*.
-- Stand-ins until named: soft sandstone `sand`, clay and the popcorn crust
-- `dry_clay`, chert `gravel`, the petrified trunks `granite`; the stunted
-- trees are the mesa's juniper nodes.
block("volcanic_ash", "Volcanic ash", "Pale grey bands of old ash between the clays.", { hardness = 0.6, tint = ROCK })
block("charcoal", "Charcoal clay", "Stark near-black bands in the badlands' hills.", { hardness = 0.7, tint = ROCK })
block("dried_mud", "Dried mud", "Dull lavender, cracked into plates.", { hardness = 0.6, tint = SOIL })
block("dead_sagebrush", "Dead sagebrush", "Brittle grey sticks at the bottom of a gully.", { hardness = 0.1, tint = SOIL, passable = true, billboard = "cross" })

-- The Taiga (2.2). `mulch` asked for by name (2026-09-15); `tall_grass`
-- and `lichen` named in the brief with nothing to stand in for them.
-- Stand-ins until named: spruce and pine are `fir_log` and `fir_needles`,
-- peat is `black_mud`.
block("mulch", "Mulch", "Rust-brown needles and bark, acid and soft underfoot.", { hardness = 0.5, tint = SOIL })

-- The Volcanic Foothills (2.3). Three new nodes, asked for by name
-- (2026-09-15): lava rock*, pumice*, sulfur*. The ash is the badlands'
-- `volcanic_ash` (asked for there first), and the charred trees are the
-- badlands' `charcoal`.
block("lava_rock", "Lava rock", "Porous, dark, sharp: a lobe of it cooled where it ran.", { hardness = 1.3, tint = ROCK })
block("pumice", "Pumice", "Pale, light, full of holes; pebbles of it in the ash.", { hardness = 0.4, tint = ROCK })
block("sulfur", "Sulfur", "Bright orange-yellow crust round a thermal fissure; it glows a little.",
    { hardness = 0.5, tint = { strength = 0.10, scale = 64 }, light_emit = { r = 3, g = 2, b = 0 } })
-- Lava (2026-09-15, "a very rare flowing lava channel or boiling lava
-- pit"): the block a full block of the fluid is drawn as, lit, and the
-- fluid — slow and heavy, orange from inside. Since engine b6935c3
-- (2026-09-16, engine-asks 31) a fluid gives off its block's `light_emit`,
-- so a pit lights its bowl and a roofed channel its tunnel; and it is drawn
-- OPAQUE, a surface rather than a window onto the pit's floor.
block("lava", "Lava", "Drawn wherever lava is. Not something you place.", { hardness = 4.0, light_emit = { r = 15, g = 8, b = 1 } })
-- An engine older than b6935c3 refuses `opacity` as an unknown field, and a
-- mod failing here is disabled whole: register without it there.
local LAVA_FLUID = { id = "lava", material = "lava", tick_rate = 10, evaporates = 0,
    opacity = 1.0, color = { r = 240, g = 96, b = 16 } }
if not pcall(game.register_fluid, LAVA_FLUID) then
    LAVA_FLUID.opacity = nil
    game.register_fluid(LAVA_FLUID)
end
-- Metal (2026-09-16, "lava needs to create blocks that are a mix of lava
-- rock, stone, obsidian, and metal when they come into contact"): beads and
-- veins of raw metal frozen out of quenched lava. Only ever a few cells of
-- such a block (rules.lua); nothing else registered is a metal.
block("metal", "Metal", "Raw metal in beads and veins, frozen out of lava where it met water.", { hardness = 3.0, tint = ROCK })
-- Bioluminescent mushrooms (2026-09-15) on the river's wet banks.
block("glow_cap", "Glow caps", "Small pale mushrooms that glow blue-green after dark.",
    { hardness = 0.1, passable = true, billboard = "cross", light_emit = { r = 2, g = 6, b = 8 } })

-- 2.4 The Coral-Fringed Shallows. The reef's own nodes, asked for by name
-- (2026-09-15): pink algae*, and the three coral tints*. White sand, calcite
-- and the anemones are what the brief's flats and drop-off walls are made
-- of and nothing already registered stands in for them. The gravel is the
-- coast's `gravel`, the pumice the Ember Ridge's.
block("white_sand", "White sand", "Fine coral sand, almost white; the lagoon's flats and its sandspits.", { hardness = 0.4, tint = SOIL })
block("calcite", "Calcite", "The reef's own rock: pale, hard, full of old coral.", { hardness = 1.1, tint = ROCK })
block("pink_algae", "Pink algae", "Vibrant coralline crust over the reef rock.", { hardness = 0.4, tint = { strength = 0.14, scale = 96 } })
block("coral_magenta", "Magenta coral", "Elkhorn branches in vivid magenta.", { hardness = 0.6, tint = { strength = 0.14, scale = 96 } })
block("coral_cyan", "Cyan coral", "Wide table coral, spreading flat in cyan.", { hardness = 0.6, tint = { strength = 0.14, scale = 96 } })
block("coral_amber", "Amber coral", "Rounded brain coral domes in amber.", { hardness = 0.6, tint = { strength = 0.14, scale = 96 } })

-- 2.6 The Flower Forest. The trees' wood and flowers, asked for by name
-- (2026-09-15): apple*, cherry*, and their blossom; the leaves with them,
-- since a crown cannot be cut out of nothing. The birch's log is the
-- woodland's; its leaves are new, paler and finer than an oak's. The four
-- meadow flowers* are the brief's own list.
block("apple_log", "Apple log", "Short, crooked, pale-barked: an orchard tree gone wild.", { hardness = 0.9, tint = SOIL })
block("apple_leaves", "Apple leaves", "A low, broad crown of them.", { hardness = 0.2, tint = GREEN, cutout = true, sway = true })
block("apple_blossom", "Apple blossom", "White-pink blossom through the crown, and fallen under it.", { hardness = 0.2, tint = { strength = 0.10, scale = 96 }, cutout = true, sway = true })
block("cherry_log", "Cherry log", "Dark, banded bark; a wild cherry leans toward the light.", { hardness = 0.9, tint = SOIL })
block("cherry_leaves", "Cherry leaves", "Pink from the first thaw to the last of the summer.", { hardness = 0.2, tint = { strength = 0.10, scale = 96 }, cutout = true, sway = true })
block("cherry_blossom", "Cherry blossom", "Deep pink, and it drifts.", { hardness = 0.2, tint = { strength = 0.10, scale = 96 }, cutout = true, sway = true })
block("birch_leaves", "Birch leaves", "Small, bright, always moving.", { hardness = 0.2, tint = GREEN, cutout = true, sway = true })
block("allium", "Allium", "A tall stem under a violet globe of florets.", { hardness = 0.1, tint = { strength = 0.12, scale = 96 }, passable = true, sway = true, billboard = "cross" })
block("peony", "Peony", "Heavy pink blooms that nod after rain.", { hardness = 0.1, tint = { strength = 0.12, scale = 96 }, passable = true, sway = true, billboard = "cross" })
block("poppy", "Poppy", "Scarlet, on a thin hairy stem.", { hardness = 0.1, tint = { strength = 0.12, scale = 96 }, passable = true, sway = true, billboard = "cross" })
block("bluebell", "Bluebells", "Nodding violet-blue bells; they carpet the groves.", { hardness = 0.1, tint = { strength = 0.12, scale = 96 }, passable = true, sway = true, billboard = "cross" })

-- 2.8 Silverwood and 2.9 Salt Pan (2026-09-16): a lichen floor for the
-- birches, and the pan's crust. The birches are the woodland's log and
-- the Flower Forest's leaves; the pan's pools are the ocean's brine.
block("lichen", "Lichen", "A pale grey-green crust over the ground under the birches, crisp underfoot.", { hardness = 0.3, tint = { strength = 0.14, scale = 96 } })
block("salt", "Salt", "The pan's crust: white, hard, cracked into polygons, glaring in the sun.", { hardness = 0.7, tint = { strength = 0.06, scale = 128 } })

-- 3.3 Obsidian Barrens, 3.4 Geyser Basin and 3.5 Cinder Coast (2026-09-16):
-- the Ember Ridge's black glass, its hot springs' sinter and the mats that
-- grow in their runoff, and the black sand where the ridge meets its sea.
block("obsidian", "Obsidian", "Black volcanic glass in sheets and razor ridges; it breaks to an edge.", { hardness = 5.0, tint = { strength = 0.05, scale = 128 } })
-- 3.6 Heather Moor (2026-09-16): the heath's carpet and its bushes.
block("heather", "Heather", "Low wiry heath in purple flower, ankle-deep.", { hardness = 0.1, tint = { strength = 0.14, scale = 64 }, passable = true, sway = true, billboard = "cross" })
block("gorse", "Gorse", "Spiny yellow-green bush in yellow flower; it smells of coconut.", { hardness = 0.3, tint = { strength = 0.12, scale = 64 }, cutout = true, sway = true })
-- 3.9 Abyssal Trench and 3.10 Mangrove Coast (2026-09-16).
block("glow_polyp", "Glow polyp", "A small pale polyp giving off a cold blue light in the dark of the deep.", { hardness = 0.1, tint = { strength = 0.10, scale = 48 }, passable = true, sway = true, billboard = "cross", light_emit = { r = 2, g = 7, b = 11 } })
block("mangrove_log", "Mangrove log", "Dark reddish wood of the mangroves' stems and prop roots.", { hardness = 2.0, tint = { strength = 0.08, scale = 64 } })
block("mangrove_leaves", "Mangrove leaves", "Thick glossy leaves in a low roof over the tide.", { hardness = 0.2, tint = { strength = 0.12, scale = 64 }, cutout = true, sway = true })
-- 3.11 Savanna, 3.13 Peat Fen and 3.14 Redwood Stands (2026-09-16).
block("acacia_log", "Acacia log", "Dark, hard, thorny wood of the flat-topped trees.", { hardness = 2.0, tint = { strength = 0.08, scale = 64 } })
block("acacia_leaves", "Acacia leaves", "Small olive leaves in flat spreading pads.", { hardness = 0.2, tint = { strength = 0.12, scale = 64 }, cutout = true, sway = true })
block("reeds", "Reeds", "Tall reeds with brown plumes, standing in the shallows.", { hardness = 0.1, tint = { strength = 0.12, scale = 64 }, passable = true, sway = true, billboard = "cross" })
block("redwood_log", "Redwood log", "Thick, soft, deeply furrowed red bark.", { hardness = 2.0, tint = { strength = 0.08, scale = 96 } })
block("redwood_needles", "Redwood needles", "Flat sprays of dark needles, high overhead.", { hardness = 0.2, tint = { strength = 0.12, scale = 64 }, cutout = true, sway = true })
block("dark_sand", "Dark sand", "Basalt ground to sand by the surf, glittering with glass.", { hardness = 0.5, tint = { strength = 0.08, scale = 96 } })

-- Water: the block a full block of the fluid is drawn as, and the fluid.
block("water", "Water", "Drawn wherever water is. Not something you place.",
    { hardness = 0.1, transparent = true })
game.register_fluid{
    id = "water",
    material = "water",
    tick_rate = 2,
    evaporates = 0,
    color = { r = 40, g = 90, b = 140 },
}
-- Brine: the deep ocean's pools. A second fluid, because fluids do not mix
-- (a block holding one accepts none of another), so a pool of it under the
-- sea stays a pool. Heavy and slow, and dark from inside. Drawn as the water
-- block until the designer names one for it.
game.register_fluid{
    id = "brine",
    material = "water",
    tick_rate = 8,
    evaporates = 0,
    color = { r = 24, g = 44, b = 52 },
}

-- The ores (2026-09-17, "a basic list of ores ... distribute them at
-- various depths below the world", in the designer's order of depth):
-- copper, iron, flint; coal, salt; tin, silver; chromium, lead; gold;
-- diamond; orichalcum. Each from its level downward, as veins and clusters
-- of cells inside blocks of whatever rock is there (generate.lua, ORES).
-- The salt is the pan's `salt`. Eleven new nodes, asked for by name.
block("copper_ore", "Copper ore", "Green-crusted rusty veins through the stone; the first metal.", { hardness = 1.6, tint = ROCK })
block("iron_ore", "Iron ore", "Dull red-brown bands and lumps in the rock.", { hardness = 1.8, tint = ROCK })
block("flint", "Flint", "Dark glassy nodules; it knaps to an edge and strikes a spark.", { hardness = 1.4, tint = ROCK })
block("coal", "Coal", "Black seams, soft and sooty.", { hardness = 1.2, tint = { strength = 0.10, scale = 64 } })
block("tin_ore", "Tin ore", "Grey-white streaks; with copper it is bronze.", { hardness = 1.7, tint = ROCK })
block("silver_ore", "Silver ore", "Pale threads and wires through dark rock.", { hardness = 2.0, tint = ROCK })
block("chromium_ore", "Chromium ore", "Hard grey-green crystals in the deep stone.", { hardness = 2.4, tint = ROCK })
block("lead_ore", "Lead ore", "Heavy, dull, blue-grey cubes.", { hardness = 1.9, tint = ROCK })
block("gold_ore", "Gold ore", "Flecks and stringers of yellow in white quartz.", { hardness = 2.2, tint = ROCK })
block("diamond", "Diamond", "A few bright cells in the dark of the Gloam; almost never a whole block.", { hardness = 3.5, tint = { strength = 0.06, scale = 32 } })
block("orichalcum", "Orichalcum", "The old metal: red-gold, warm, faintly lit from within, deeper than anything.",
    { hardness = 4.0, tint = { strength = 0.08, scale = 48 }, light_emit = { r = 4, g = 2, b = 1 } })

-- The normal caves (2026-09-18), one new material and one new plant a
-- biome at most: 2.1 Mossy Limestone's `maidenhair` (its limestone is
-- `calcite`), 2.2 Crystal Seam's `crystal`, 2.3 Underground River's
-- `cobbles` and `glow_algae`.
block("maidenhair", "Maidenhair fern", "Fragile micro-ferns a hand high, where the drips fall.",
    { hardness = 0.1, tint = { strength = 0.12, scale = 32 }, passable = true, sway = true, billboard = "cross" })
block("crystal", "Crystal", "Clear hexagonal prisms grown out of the seam; they catch a light and hold it.",
    { hardness = 2.6, transparent = true, tint = { strength = 0.06, scale = 24 }, light_emit = { r = 2, g = 3, b = 5 } })
block("cobbles", "Cobbles", "Rounded river cobbles, grey and brown, packed in the bed.", { hardness = 0.8, tint = ROCK })
block("glow_algae", "Glowing algae", "A slick dark-green film on the waterline's stones, lit from within.",
    { hardness = 0.1, tint = { strength = 0.10, scale = 24 }, light_emit = { r = 1, g = 6, b = 3 } })

-- Depth bands -----------------------------------------------------------
block("dark_sediment", "Dark sediment", "Dark-cave rock, 1.6 to 4 km down: old mud turned to stone.", { hardness = 2.0, tint = ROCK })
block("light_sediment", "Light sediment", "Pale beds laid through the dark sediment.", { hardness = 2.0, tint = ROCK })
block("morphic_rock", "Morphic rock", "Pressure-crushed rock, below 4 km.", { hardness = 3.0, tint = ROCK })

-- The magma shell: a thin lava layer with a crust on each side ----------
block("magma_crust", "Magma crust", "Cooked rock, fifty blocks either side of the fire.", { hardness = 2.5 })
block("magma", "Magma", "Still lava. A look-alike solid until fluid can be generated.",
    { hardness = 4.0, light_emit = { r = 15, g = 7, b = 0 } })

-- The core stack --------------------------------------------------------
block("hot_fiber_stone", "Hot fiber stone", "Hot magical caves: it glows.",
    { hardness = 2.0, light_emit = { r = 10, g = 8, b = 4 } })
block("caul", "Caul", "The slime border: a luminous membrane.",
    { hardness = 0.8, light_emit = { r = 4, g = 9, b = 3 } })
block("cold_fiber_stone", "Cold fiber stone", "Cold magical caves: ice-lit.",
    { hardness = 2.0, light_emit = { r = 3, g = 5, b = 9 } })
block("scorch", "Scorch", "The hollow ring: dense, hot, dry.", { hardness = 3.5, tint = ROCK })

-- The tail --------------------------------------------------------------
block("marrow", "Marrow", "White porous stone of the tail.", { hardness = 1.2, tint = ROCK })
block("apex_stone", "Apex stone", "What the needle is made of at the end.", { hardness = 5.0 })

game.log("tiamot_default_world: registered placeholder blocks")

return M
